name: PHP Compatibility

on: [push, pull_request]

jobs:
  php_compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.4", "8.0", "8.1", "8.2"]
      fail-fast: false  # продолжать проверку остальных версий при падении одной

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Check PHP version
        run: php -v

      - name: Lint PHP files
        run: find . -type f -name "*.php" -print0 | xargs -0 -n1 -P4 php -l
